# todo api
# testUser eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk3MzgyMzE3LCJpYXQiOjE2OTcyOTU5MTcsImp0aSI6ImJkMWE5NzgzYTE5YTQxYTBhYjYwZmZlNzBkOGU3YTU1IiwidXNlcl9pZCI6MiwidXNlcm5hbWUiOiJ0ZXN0VXNlciJ9.H8wTyeCOGfIU5PsQtSbvg4M2buC-QTgsj01Lsqjhgxk
# siddid eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk3MzcxNDc5LCJpYXQiOjE2OTcyODUwNzksImp0aSI6IjY3NTQwMmE5MTY2OTQxNGFiYTdmMTg5MGJmMTNjOTc3IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJzaWRkaWQifQ.gCI3UCzQ9tvd4kUlPcoDi8B6X0Fq2s_RwwjgOhXG9pc

###
# @name task-list
GET http://127.0.0.1:8000/api/task-list/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk3MzcxNDc5LCJpYXQiOjE2OTcyODUwNzksImp0aSI6IjY3NTQwMmE5MTY2OTQxNGFiYTdmMTg5MGJmMTNjOTc3IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJzaWRkaWQifQ.gCI3UCzQ9tvd4kUlPcoDi8B6X0Fq2s_RwwjgOhXG9pc
Content-Type: application/json
###

#@name task-detail
GET http://127.0.0.1:8000/api/task-detail/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk3MzcxNDc5LCJpYXQiOjE2OTcyODUwNzksImp0aSI6IjY3NTQwMmE5MTY2OTQxNGFiYTdmMTg5MGJmMTNjOTc3IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJzaWRkaWQifQ.gCI3UCzQ9tvd4kUlPcoDi8B6X0Fq2s_RwwjgOhXG9pc
Content-Type: application/json
###

#@name task-create

POST http://localhost:8000/api/task-create/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk3MzgyMzE3LCJpYXQiOjE2OTcyOTU5MTcsImp0aSI6ImJkMWE5NzgzYTE5YTQxYTBhYjYwZmZlNzBkOGU3YTU1IiwidXNlcl9pZCI6MiwidXNlcm5hbWUiOiJ0ZXN0VXNlciJ9.H8wTyeCOGfIU5PsQtSbvg4M2buC-QTgsj01Lsqjhgxk
Content-Type: application/json

{
  "title": "test 7",
  "description": "testing 7",
  "deadline": "2023-10-14",
  "reminder_time": "2023-10-14T11:52:38Z",
  "completed": false,
  "priority": "low"
}

###

#@name task-update

PUT http://localhost:8000/api/task-update/3/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk3MzcxNDc5LCJpYXQiOjE2OTcyODUwNzksImp0aSI6IjY3NTQwMmE5MTY2OTQxNGFiYTdmMTg5MGJmMTNjOTc3IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJzaWRkaWQifQ.gCI3UCzQ9tvd4kUlPcoDi8B6X0Fq2s_RwwjgOhXG9pc
Content-Type: application/json

{
  "title": "test 2",
  "description": "testing 2",
  "deadline": "2023-10-14",
  "reminder_time": "2023-10-14T11:52:38Z",
  "completed": false,
  "priority": "low"
}

###

#@name task-delete

DELETE http://localhost:8000/api/task-delete/5/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjk3MzcxNDc5LCJpYXQiOjE2OTcyODUwNzksImp0aSI6IjY3NTQwMmE5MTY2OTQxNGFiYTdmMTg5MGJmMTNjOTc3IiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJzaWRkaWQifQ.gCI3UCzQ9tvd4kUlPcoDi8B6X0Fq2s_RwwjgOhXG9pc
Content-Type: application/json

###

#@name token
POST http://localhost:8000/api/token/
Content-Type: application/json

{
  "username": "testUser",
  "password": "test@123"
}

###

#@name token-refresh
POST http://localhost:8000/api/token/refresh/
Content-Type: application/json

{
  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTcwNTA4NjU5MywiaWF0IjoxNjk3MzEwNTkzLCJqdGkiOiIzZGFmMzIzNDdlYjU0MTQyYTlkMTljMmQ5YTZlOTE5MyIsInVzZXJfaWQiOjIsInVzZXJuYW1lIjoidGVzdFVzZXIifQ.VyLd9IW49rz5X-8q6SMUj3iExCRapsCPx0W3Ekr2ph4"
}

###
#@name user-create
POST http://localhost:8000/api/user/create/
Content-Type: application/json

{
  "username": "newUser1",
  "email": "newuser7@email.com",
  "password": "test@1234",
  "password2": "test@123"
}